### ISSUE TITLE
ltex-ls always fails the test when initiation

### ISSUE THREAD

**Issue by jonas-tzhang** [valentjn/languagetool-languageserver#165] opened 2022-04-04 08:37 UTC
Hi! I have tried online installation and offline installation but both failed. The output is as follows,

2022-04-04T08:28:16.349Z Info: Setting LTeX UI language to 'zh-cn'.
2022-04-04T08:28:16.349Z Info: Loading i18n messages...
2022-04-04T08:28:16.350Z Info: Loading default i18n messages...
2022-04-04T08:28:16.352Z Info: 
2022-04-04T08:28:16.352Z Info: ltex.ltex-ls.path not set.
2022-04-04T08:28:16.352Z Info: Searching for ltex-ls in 'c:\Users\userName\.vscode\extensions\valentjn.vscode-ltex-13.1.0\lib'...
2022-04-04T08:28:16.352Z Info: ltex-ls found in 'c:\Users\userName\.vscode\extensions\valentjn.vscode-ltex-13.1.0\lib\ltex-ls-15.2.0'.
2022-04-04T08:28:16.352Z Info: 
2022-04-04T08:28:16.352Z Info: Using ltex-ls from 'c:\Users\userName\.vscode\extensions\valentjn.vscode-ltex-13.1.0\lib\ltex-ls-15.2.0'.
2022-04-04T08:28:16.352Z Info: Using Java bundled with ltex-ls as ltex.java.path is not set.
2022-04-04T08:28:16.353Z Info: Testing ltex-ls...
2022-04-04T08:28:16.353Z Info:   Command: "c:\\Users\\userName\\.vscode\\extensions\\valentjn.vscode-ltex-13.1.0\\lib\\ltex-ls-15.2.0\\bin\\ltex-ls.bat"
2022-04-04T08:28:16.353Z Info:   Arguments: ["--version"]
2022-04-04T08:28:16.353Z Info:   env['JAVA_HOME']: undefined
2022-04-04T08:28:16.353Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2022-04-04T08:28:16.950Z Error: Test failed.
2022-04-04T08:28:16.950Z Error: Error details:
2022-04-04T08:28:16.950Z Info: ltex-ls did not print expected version information to stdout.
2022-04-04T08:28:16.950Z Info: stdout of ltex-ls:
2022-04-04T08:28:16.950Z Info: Active code page: 65001
2022-04-04T08:28:16.950Z Info: {
2022-04-04T08:28:16.950Z Info:   "ltex-ls": "15.2.0",
2022-04-04T08:28:16.950Z Info:   "java": "11.0.12"
2022-04-04T08:28:16.950Z Info: }
2022-04-04T08:28:16.950Z Info: 
2022-04-04T08:28:16.950Z Info: stderr of ltex-ls:
2022-04-04T08:28:16.950Z Info: 
2022-04-04T08:28:16.950Z Info: You might want to try offline installation, see https://valentjn.github.io/vscode-ltex/docs/installation-and-usage.html#offline-installation.

How can I fix this? Thanks a lot!

**Comment by valentjn** [comment] 2022-04-04 11:50
Duplicate of valentjn/vscode-ltex#185 with [the solution here](https://github.com/valentjn/vscode-ltex/discussions/185#discussioncomment-180321).

**Closed as completed** 2022-04-04 11:51 UTC
Labels: 1-question ❓, 3-duplicate

**Comment by jonas-tzhang** [comment] 2022-04-04 12:46
Thanks for your reply, problem solved!
