### ISSUE TITLE
Symbol picking doesn't work under Helix (and maybe others) client

### ISSUE THREAD

**Issue by Kenneth-Mata** [valentjn/languagetool-languageserver#200] opened 2022-11-17 18:09 UTC
**Describe the bug**
When using with [Helix](https://github.com/helix-editor/helix) text editor and trying to use the Symbol picker, it shows nothing

**Steps to reproduce**

1. Open any .md file using Helix
2. input Space + s to open the Symbol Picker
3. Is empty

**Expected behavior**
The symbol picker shows the headings as symbols

**LTeX configuration**
Please paste all configuration settings starting with `ltex.` from your `settings.json`. You can help us by temporarily removing some irrelevant settings from your `settings.json` and see if the bug still occurs.

<details>

```
{
  "programName": "ltex-cli",
  "helpMessage": {
    "description": "LTeX CLI - Command-line interface for LTeX LS",
    "visibleArguments": [
      "--client-configuration",
      "--verbose"
    ]
  },
  "defaultValues": {
    "--hide-commands": true,
    "--server-command-line": "./ltex-ls"
  }
}
```

</details>

**LTeX LS log**
Paste the log (output) of LTeX LS here: i will provide the log of Helix as it calls into ltex-ls as i can't find an ltex log in the system

<details>

```
2022-11-15T21:40:45.980 helix_lsp::transport [ERROR] err <- "Nov 15, 2022 9:40:45 PM org.bsplines.ltexls.server.LtexLanguageServer initialize\n"
2022-11-15T21:40:45.981 helix_lsp::transport [ERROR] err <- "INFO: ltex-ls 15.2.0 - initializing...\n"
2022-11-15T21:40:46.473 helix_lsp::transport [ERROR] err <- "Nov 15, 2022 9:40:46 PM org.bsplines.ltexls.server.DocumentChecker logTextToBeChecked\n"
2022-11-15T21:40:46.473 helix_lsp::transport [ERROR] err <- "FINE: Checking the following text in language 'en-US' via LanguageTool: \".. \"... (truncated to 100 characters)\n"
2022-11-15T21:40:55.454 helix_lsp::transport [ERROR] err <- "Nov 15, 2022 9:40:55 PM org.bsplines.ltexls.server.DocumentChecker checkAnnotatedTextFragment\n"
2022-11-15T21:40:55.454 helix_lsp::transport [ERROR] err <- "FINE: Obtained 45 rule matches\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "Nov 15, 2022 9:41:38 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "SEVERE: Internal error: java.lang.NullPointerException\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "java.util.concurrent.CompletionException: java.lang.NullPointerException\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(Unknown Source)\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(Unknown Source)\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "\tat java.base/java.util.concurrent.CompletableFuture.thenAccept(Unknown Source)\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:279)\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)\n"
2022-11-15T21:41:38.762 helix_lsp::transport [ERROR] err <- "\tat java.base/java.util.concurrent.FutureTask.run(Unknown Source)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat java.base/java.lang.Thread.run(Unknown Source)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "Caused by: java.lang.NullPointerException\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.adapters.HoverTypeAdapter.writeContents(HoverTypeAdapter.java:82)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.adapters.HoverTypeAdapter.write(HoverTypeAdapter.java:142)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.adapters.HoverTypeAdapter.write(HoverTypeAdapter.java:38)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat com.google.gson.TypeAdapter$1.write(TypeAdapter.java:191)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat com.google.gson.Gson.toJson(Gson.java:735)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:423)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:55)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat com.google.gson.Gson.toJson(Gson.java:735)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat com.google.gson.Gson.toJson(Gson.java:714)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.serialize(MessageJsonHandler.java:145)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.serialize(MessageJsonHandler.java:140)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:59)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$handleRequest$1(RemoteEndpoint.java:281)\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\t... 14 more\n"
2022-11-15T21:41:38.763 helix_lsp::transport [ERROR] err <- "\n"
2022-11-15T21:41:38.770 helix_lsp::transport [ERROR] <- InternalError: Internal 
```

</details>

**Version information**
List here the version information of the relevant software.

- Operating system: Linux (Fedora 36)
- ltex-ls: 15.2.0
- Java: 11.0.12

**Comment by David-Else** [comment] 2023-01-02 17:05
In the latest version of Helix it reports `Language server does not support document symbols`, so it is not a bug, but a feature that needs adding.

**Comment by David-Else** [comment] 2023-03-17 11:41
@Kenneth-Mata With https://github.com/helix-editor/helix/pull/2507 you can use marksman (that does show symbols) with ltex-ls. I don't know if it is the job of ltex-ls to show symbols? Anyway, I think that PR will be merged soon and all will be well, here is my current config that works great with the PR:

```
[language-server.ltex-ls]
command = "ltex-ls"

[language-server.ltex-ls.config]
ltex.disabledRules = { "en-US" = [
  "PROFANITY",
], "en-GB" = [
  "PROFANITY",
] }
ltex.dictionary = { "en-US" = [
  "builtin",
], "en-GB" = [
  "builtin",
] } 

# Configure languages

[[language]]
name = "git-commit"
language-servers = [ "ltex-ls" ]

[[language]]
name = "markdown"
language-servers = [  "ltex-ls", "marksman" ]
text-width = 80
formatter = { command = 'prettier', args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "never",        # <always|never|preserve>
] }
```

**Comment by sbromberger** [comment] 2024-03-03 22:03
@David-Else - sorry to jump in on your comment with a question, but what do the directives in `[language-server.ltex-ls.config]` do? I've tried modifying the `ltex.dictionary` key but it doesn't seem to have an effect. (I'm trying to get the "add to dictionary" action to work). I'm using helix built from master a few days ago (so nominally 23.10).

**Comment by David-Else** [comment] 2024-03-04 11:08
@sbromberger Unfortunately add to dictionary won't work in Helix at the moment as it is not a standard LSP action, it would need a plugin. My current config that is working for the latest master is:

```
[language-server.ltex-ls.config]
ltex.diagnosticSeverity = "warning" 
ltex.disabledRules = { "en-US" = ["PROFANITY"], "en-GB" = ["PROFANITY"] }
ltex.dictionary = { "en-US" = ["builtin", "Lazygit", "chainable", "textobject", "textobjects", "togglable", "Deno"  ], "en-GB" = ["builtin", "Lazygit", "chainable", "textobject", "textobjects", "togglable", "Deno" ] }
```
I hope that helps in some way :)

**Closed as completed** 2024-12-23 06:15 UTC
Labels: 1-bug 🐛, 2-unconfirmed
