### ISSUE TITLE
Commit hook/CI support

### ISSUE THREAD

**Issue by katzimoto** [valentjn/languagetool-languageserver#73] opened 2021-07-03 10:53 UTC
Does it possible to create a commit hook that can be used on pre-commit/CI service to keep my repository from grammar mistakes?
I saw it on another projects as linters and I think it's would be great if I could avoid from grammar mistakes automatically.

**Comment by valentjn** [comment] 2021-07-05 12:16
What you basically want is a CLI-based way to interact with LT<sub>E</sub>X LS. This will certainly be possible once #71 is implemented. You should then be able to write Bash scripts and YAML files that use LT<sub>E</sub>X LS for Git hooks and CI, respectively.

Closing as duplicate of #71.

**Closed as completed by valentjn** 2021-07-05 12:16 UTC
Labels: 1-feature-request ✨, 3-duplicate
