### ISSUE TITLE
Asciidoctor support

### ISSUE THREAD

**Issue by marioortizmanero** [valentjn/languagetool-languageserver#148] opened 2022-01-31 17:21 UTC
It would be awesome to have support for [asciidoctor](https://asciidoctor.org/) as a format, the same way as we already have it for markdown or org mode. It's somewhat similar to org in the sense that it's richer than markdown, but not as complex as latex.

**Comment by marioortizmanero** [comment] 2022-02-07 12:43
Note that this could perhaps use [asciidoctorj](https://github.com/asciidoctor/asciidoctorj) to parse the contents? AFAIK it can be used to [read the document tree](https://docs.asciidoctor.org/asciidoctorj/latest/read-document-tree/). I haven't tried it, but I'm sure that it's better than reinventing the wheel.

**Comment by valentjn** [comment] 2022-02-23 15:21
This is already tracked for vscode-ltex in valentjn/ltex-ls#220, closing this in favor of that issue.

**Comment by valentjn** [comment] 2022-02-23 15:22
Duplicate of valentjn/ltex-ls#220

**Closed as completed by valentjn** 2022-02-23 15:21 UTC
Labels: 1-feature-request ✨, 3-duplicate

**Comment by marioortizmanero** [comment] 2022-02-23 15:51
Sure, but it should work for `ltex-ls` itself, not just vscode (I use nvim with ltex-ls)
